services:
  backend:
    build:
      context: .
      dockerfile: dev.DockerFile
    container_name: backend-auth
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
    restart: unless-stopped
    networks:
      - backend-net

networks:
  backend-net: